name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: [ "HW.c" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile
      run: gcc HW.c unit_tests.c -o test

    - name: Run tests
      id: test
      run: |
        ./test > test_output.txt

    - name: Analyze test output
      run: |
        failed_tests=$(grep -wn "Assertion failed" test_output.txt || true)
        if [ -n "$failed_tests" ]; then
          echo "❌ Tests failed:"
          echo "$failed_tests"
          exit 1
        else
          echo "✅ All tests passed!"
          exit 0
        fi