name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths: [ "HW.c" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile
      run: gcc HW.c unit_tests.c -o test

    - name: Run tests
      run: ./test